add docker config
openstax/rex-web pull request #10
Opened 2018-11-13 22:08 UTC by TomWoodward

@philschatz i moved your dev server to a new home so i could share it with the docker config. in the future we'll add proxy middleware that can be shared between docker, tests, and dev.

also jq was just straight not working so i replaced with a custom postinstall script

2018-11-13 22:20 UTC, philschatz requested changes
Yay! It works for me. Should docker instructions be included in the README?

2018-11-13 22:20 UTC, philschatz commented on Dockerfile
> +CMD yarn server
```suggestion
CMD yarn run server
```

2018-11-13 22:20 UTC, philschatz commented on Dockerfile
> +RUN yarn && yarn build
Just to clarify to people not necessarily familiar with yarn's commandline syntax. What do you think?

```suggestion
RUN yarn install
RUN yarn run build
```

2018-11-14 01:13 UTC, TomWoodward commented
@philschatz added readme and rejiggered the structure a little bit.

i made `yarn run` the entrypoint so that in the future we could do `docker run openstax/books-web pre-render`. `server` is still the default command.

i almost added `docker run openstax/books-web test` as an example command but it doesn't work. i'll need to extend the dockerfile a bit to install chrome and stuff for puppeteer to work. i'll work on that tomorrow.

2018-11-14 15:36 UTC, TomWoodward commented
ui tests work in the docker container now

2018-11-14 17:02 UTC, philschatz approved these changes

2018-11-14 17:21 UTC, merged