Update ArchivePage and Page types
openstax/rex-web pull request #1169
Opened 2021-05-05 14:53 UTC by PiotrKozlowski

for: https://github.com/openstax/unified/issues/1555

2021-05-06 14:35 UTC, TomWoodward requested changes

2021-05-06 14:35 UTC, TomWoodward commented on src/test/mocks/archiveLoader.ts
> +        id: `${newPage.id}@${newPage.revised}`,
it might be more realistic to just hardcode this to like `@1.0` or something, at least then it'll be the right format

2021-05-07 13:36 UTC, TomWoodward requested changes

2021-05-07 13:47 UTC, PiotrKozlowski commented on src/test/fixtures/apps/archive/codeversion/contents/testbook1-shortid:testpage2-shortid.json
> +  "slug": "testbook1-testpage2-uuid"
right, thanks

2021-05-07 16:46 UTC, TomWoodward approved these changes

2021-05-07 16:46 UTC, merged