Speed up loading books on dev homepage
openstax/rex-web pull request #1175
Opened 2021-05-07 13:40 UTC by PiotrKozlowski

There is no card for this. It is just something that was annoying for me. I don't want to wait for all books to load because I'm usually testing on American Government 2e

2021-05-07 13:56 UTC, jarosik10 commented
Yay, I'd be helpful. You have to add/change some tests for 100% coverage. ;)

2021-05-07 14:31 UTC, TomWoodward requested changes
if you use the other url https://rex-web.herokuapp.com/books/list the sw caches the requests and its way faster

2021-05-07 14:31 UTC, TomWoodward commented on src/app/developer/components/Books.tsx
> +    const sortBooks = (bookA: Book, bookB: Book) => {
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/localeCompare does this in one line

2021-05-10 12:51 UTC, PiotrKozlowski commented
@jarosik10 
> Yay, I'd be helpful. You have to add/change some tests for 100% coverage. ;)

Done

2021-05-10 13:08 UTC, jarosik10 approved these changes

2021-05-11 12:19 UTC, TomWoodward approved these changes

2021-05-11 12:20 UTC, merged