Set order of TOC button to initial value in page not found text
openstax/rex-web pull request #1254
Opened 2021-07-22 14:52 UTC by jarosik10

2021-07-22 15:10 UTC, bethshook approved these changes

2021-07-27 13:37 UTC, TomWoodward requested changes

2021-07-27 13:37 UTC, TomWoodward commented on src/app/content/components/Page/PageNotFound.tsx
> +    order: initial;
instead of setting the order in the control, and overriding it here, it'd be better to only set it where its needed

2021-07-27 14:02 UTC, jarosik10 commented on src/app/content/components/Toolbar/styled.tsx
> +// tslint:disable-next-line:variable-name
I've moved it down because `SidebarControl` has to be defined before being used.

2021-07-27 14:02 UTC, jarosik10 commented on src/app/content/components/Toolbar/styled.tsx
> +export const TopBar = styled.div`
I've moved it down because SidebarControl has to be defined before being used.

2021-07-29 19:20 UTC, TomWoodward requested changes
ok so i'm sorry the situation was worse initially than i thought and i think i led you astray. the page not found is using `toolbar/SidebarControl` which is itself a customization of the styles from `components/SidebarControl`. it makes sense for `toolbar/SidebarControl` to include all the custom styling for being in the toolbar, including the order attribute. i think the issue is that the page not found shouldn't be using this customized style, it should be using the base component from `components/SidebarControl`

2021-08-03 14:30 UTC, jarosik10 commented on src/app/content/components/Page/PageNotFound.tsx
> +    <OpenSidebarControl hideMobileText={false}/>
@TomWoodward 
Do we want to always keep the text or make the sidebar control to behave and look same as in toolbar?

2021-08-10 13:49 UTC, TomWoodward approved these changes

2021-08-10 13:49 UTC, merged