Add section type to TOC
openstax/rex-web pull request #1390
Opened 2021-12-01 20:51 UTC by bethshook

for: openstax/unified#1762

2021-12-07 14:31 UTC, jarosik10 requested changes
Looks good. Fix test coverage please.

Do you know where can I find a book with a `eoc-dropdown`?

2021-12-07 18:30 UTC, bethshook commented
Coverage fixed. Calculus TOC has both kinds of dropdowns.

2021-12-09 13:37 UTC, jarosik10 requested changes

2021-12-09 15:15 UTC, jarosik10 approved these changes

2021-12-09 15:15 UTC, bethshook commented on src/app/content/types.ts
> +export type ArchiveTreeSectionType = 'book' | 'unit' | 'chapter' | 'page' | 'eoc-dropdown' | 'eob-dropdown' | null;
fixed

2021-12-09 16:30 UTC, merged