Add data analytics region to key terms results
openstax/rex-web pull request #1405
Opened 2022-01-05 21:35 UTC by bethshook

2022-01-05 21:42 UTC, bethshook commented
@TomWoodward currently there's a region `search-results` on the parent of all results. do we want a `content-results` region for non-kt results?

2022-01-06 16:21 UTC, TomWoodward requested changes
pretty sure it just goes up to the nearest region tag, so you may want to make your kt one more specific, like `kt-search-results`. you could also add the `content-search-results` if you wanted.... that is more specific, and specific is good, but it would also change the category on the event and cause a disconnect in the historical data... maybe thats a good thing since we're causing a disconnect anyway by moving the kt results out of that category

i think you can go ahead and add the new label for the content results section and definitely leave the existing one on the whole sidebar so it catches things like the sidebar close button

2022-01-06 19:25 UTC, bethshook commented
I'm realizing that the markup for the search results is screwed up such that adding a region for non-KT results is not currently possible. Should I attempt to fix this here or create a separate issue? Alternatively I could add it to [this list](https://app.zenhub.com/workspaces/openstax-unified-5b71aabe3815ff014b102258/issues/openstax/unified/1750).

```
<ol class="NavOl">
   <div class="RelatedKeyTerms">
      Key Term
      Key Term
   </div>
   <span>Chapter Results</span>
   <li>Result</li>
   <li>Result</li>
</ol>
```

2022-01-10 18:24 UTC, TomWoodward approved these changes

2022-01-12 16:15 UTC, merged