Footer
openstax/rex-web pull request #143
Opened 2019-05-16 06:49 UTC by KarinaMendez2

2019-05-17 14:18 UTC, TomWoodward requested changes

2019-05-17 14:18 UTC, TomWoodward commented on src/app/content/components/Footer.tsx
> +import React, { Component } from 'react';
cc is complaining about the length of this file, i've been doing a thing where i move the styled components to a different file in the format of 

`Footer/index.js` <- no styled components, just assemble the styled components and put any required js shenanigans
`Footer/styled.js` <- export the styled components, try not to put anything in here that isn't styled component definitions

2019-05-17 14:18 UTC, TomWoodward commented on src/app/content/components/Footer.tsx
> +const mobileMinWidth = '37.5';
i feel like these magic numbers should be derived from other content styles

2019-05-17 14:18 UTC, TomWoodward commented on src/app/content/components/Footer.tsx
> +    public render() {
can break this render function up into a few chunks so that cc stop complaining about 135 line functions

2019-05-17 14:18 UTC, TomWoodward commented on src/app/content/components/Footer.tsx
> +export class Footer extends Component<any> {
can use a SFC here

2019-05-17 14:18 UTC, TomWoodward commented on src/app/messages/en/messages.json
> +  "i18n:footer:donate-link:today": " today",
you can combine these 3 into 1, check out attribution text configs

2019-05-20 15:09 UTC, TomWoodward requested changes

2019-05-20 15:09 UTC, TomWoodward commented on src/app/content/components/Content.tsx
> +import Footer from './Footer/index';
you don't have to do this, it'll figure out the index file automatically

2019-05-20 15:16 UTC, TomWoodward requested changes
can we move the footer from `/src/app/content/components/` to `/src/app/components` ? the content module is supposed to be just stuff that has to do with the book content

2019-05-21 16:04 UTC, TomWoodward requested changes

2019-05-29 17:14 UTC, TomWoodward commented
somehow the bottom line in the copyrights box is still 3px taller on rex than it is on the cms

2019-05-29 17:14 UTC, TomWoodward commented
the size of the social icons is wrong

2019-05-29 17:18 UTC, TomWoodward commented
there is a screen size where the top margin in the footer disappears 
![image](https://user-images.githubusercontent.com/636227/58577336-357f4200-8214-11e9-938f-2c556914b8ab.png)

2019-05-30 19:10 UTC, kjdav commented
this looks good @KarinaMendez @TomWoodward

2019-05-31 14:21 UTC, TomWoodward commented
@KarinaMendez lets get the tests passing on this so we can merge it

2019-06-03 17:01 UTC, TomWoodward requested changes

2019-06-03 17:04 UTC, KarinaMendez2 commented on src/app/components/Footer/index.screenshotspec.ts
> +  return window && document && document.documentElement && window.scrollBy(0, document.documentElement.scrollHeight);
I tried running the screenshots importing that function that exists in another file but didn't work

2019-06-03 17:48 UTC, TomWoodward approved these changes

2019-06-03 19:50 UTC, merged