Principles of Accounting, Volume 1: Financial Accounting updates
openstax/rex-web pull request #1442
Opened 2022-02-10 06:06 UTC by staxbot

2022-02-11 17:50 UTC, ne-newton requested changes
We can't merge this until the licensing bug is fixed

2022-02-14 15:19 UTC, TomWoodward requested changes
pending license issue fix

2022-03-16 20:37 UTC, Malar-Natarajan approved these changes

2022-03-16 20:39 UTC, Malar-Natarajan approved these changes

2022-03-16 20:43 UTC, TomWoodward approved these changes

2022-03-16 20:43 UTC, merged