fix: open in new tab
openstax/rex-web pull request #169
Opened 2019-06-06 16:36 UTC by philschatz

Command-clicking on links to make them open in a new tab did not work because the ContentLink handler consumed the event.

2019-06-06 16:52 UTC, TomWoodward requested changes
i think the logic in the `Page` component which handles clicking content links inside the body of the content will still be broken.

i think the logic in Page and in ContentLink is similar enough that we should try to share it between these two places

2019-06-06 18:55 UTC, philschatz commented
I fixed the links in `Page` content. I like the idea of combining the logic since it does the same thing in 2 different places but I had trouble resolving the fact that the event has 2 different types: React.MouseEvent<HTMLAnchorElement>` and `dom.MouseEvent`. Any ideas on resolving those 2 types? Maybe an Interface would work?

2019-06-07 14:01 UTC, TomWoodward commented
looking more closely, the two blocks of code are not as similar as i remembered. they're similar, but each has bits of code that the other does not and the shared logic is only like 3 statements (and the data for navigate is compiled differently). i think it is fine to leave them separate for now.

2019-06-07 14:01 UTC, TomWoodward approved these changes

2019-06-10 18:01 UTC, merged