Async/defer scripts
openstax/rex-web pull request #1803
Opened 2022-12-21 17:12 UTC by Dantemss

For: https://github.com/openstax/unified/issues/1964

- Made googleoptimize async

TODO:

- Pulse Insights
- Webpack chunks
- Test

2022-12-21 19:26 UTC, Dantemss commented
Pulse Insights was already async even before this PR

2022-12-21 22:57 UTC, Dantemss commented
I thought I was issues in the dev home page on Heroku and a bunch of console warnings in a book, but maybe that happened because it was still being deployed, they seem to be gone now...

2023-01-04 14:12 UTC, TomWoodward requested changes
you may also need to add here 
https://github.com/openstax/rex-web/blob/main/script/prerender/contentPages.tsx#L247

2023-01-09 23:21 UTC, Dantemss commented on script/prerender/contentPages.tsx
> +  html = html.replace(/(<script defer="defer" src="[^"]+\.chunk\.js"><\/script>)/, scripts.join('') + '$1');
The htmlWebpackPluginInstance config in the craco config renders the `defer="defer"` but seems like that is standard or something, though the inconsistency of the boolean attributes here bothers me a little.

2023-01-09 23:41 UTC, Dantemss commented
Ah right no prerendering on Heroku to test that part...

2023-01-13 01:31 UTC, jivey approved these changes
Not sure if @TomWoodward had some more feedback, but this seems good to me. I wasn't able to test locally but can take a close look when it's on staging.

2023-01-25 14:24 UTC, TomWoodward approved these changes

2023-02-13 16:35 UTC, merged