Update support center link
openstax/rex-web pull request #1898
Opened 2023-03-15 18:55 UTC by RoyEJohnson

2023-03-16 13:51 UTC, TomWoodward requested changes

2023-03-16 17:40 UTC, TomWoodward approved these changes

2023-03-16 17:59 UTC, jivey approved these changes

2023-03-22 15:32 UTC, RoyEJohnson commented on src/app/content/content.browserspec.ts
> +    expect(scrollTop).toBeLessThan(22);
I rolled back all the extraneous stuff.

2023-03-28 16:00 UTC, merged