Adjust toast top for Assigned
openstax/rex-web pull request #1922
Opened 2023-04-25 22:03 UTC by RoyEJohnson

for: unified/openstax/#2288

2023-04-27 15:33 UTC, jivey requested changes

2023-04-27 15:33 UTC, jivey commented on src/app/content/components/Assigned.tsx
> +      <Page toastTop={5.2}>
I think there's a toolbarHeight var somewhere that we could reference for this, or maybe we set one up so it's easy to adjust if the toolbar changes.

2023-04-27 15:33 UTC, jivey commented on src/app/content/components/Page/PageComponent.tsx
> +    ;
Usually creating a styled component within another component logs a console warning, you may want to move this outside of PageComponent.

2023-04-27 18:57 UTC, RoyEJohnson commented
Should be much better this time.

2023-04-28 19:17 UTC, jivey requested changes
Looking good, looks like there's just some minor lint issues: https://github.com/openstax/rex-web/actions/runs/4823447051/jobs/8591956424?pr=1922#step:6:17

And this is up to you, but we may want to make the override always 100% width, at this specific width it seems to be too narrow:
![image](https://user-images.githubusercontent.com/34174/235233798-d2504ccb-e546-4e21-aab4-8aa74a0172ea.png)

once it goes wider, it looks fine, so maybe we should override whatever the first screenshot is doing to match this: 
![image](https://user-images.githubusercontent.com/34174/235234069-bc7aa630-2890-424c-a83b-6538aac1cfd5.png)

2023-05-01 16:52 UTC, RoyEJohnson commented
I've fixed the lint complaints in files I changed, but there are some in other files I left.

2023-05-02 18:35 UTC, jivey requested changes
At first I was worried about the linter errors but I saw from your other PR that deleting node_modules fixes it.

Looks good, just one small change to fix the stylelint, I guess it doesn't like the double slashes 🤔

2023-05-02 18:35 UTC, jivey commented on src/app/content/components/Page/PageContent.tsx
> +  // stylelint-disable selector-class-pattern
```suggestion
  /* stylelint-disable selector-class-pattern */
```

2023-05-02 18:35 UTC, jivey commented on src/app/content/components/Page/PageContent.tsx
> +  // stylelint-enable selector-class-pattern
```suggestion
  /* stylelint-enable selector-class-pattern */
```

2023-05-10 13:19 UTC, jivey approved these changes

2023-08-09 14:00 UTC, merged