Pre-fetch images during prerender to prime the image-cdn cache
openstax/rex-web pull request #1940
Opened 2023-06-20 21:50 UTC by RoyEJohnson

For: https://github.com/openstax/unified/issues/2434

Is it really as simple as this, or am I missing something?

2023-06-26 05:51 UTC, jivey approved these changes
Code change looks good, I'm not sure if more is needed to make this work, maybe check with @TomWoodward

2023-06-26 11:50 UTC, TomWoodward requested changes
We only want to do this head request in prerendering, anything in the app code will also happen in end user sessions

Also, we should be including node-fetch I'm browser side code

2023-06-26 13:51 UTC, RoyEJohnson commented
Thanks, @TomWoodward, how the browser and prerender were separated was completely unclear, so this is extremely helpful.

2023-06-26 18:53 UTC, RoyEJohnson commented
I ran `prettier` on contentDOMTransformations, which is why there's so much reformatting there. I wasn't sure we wanted prefetch in `prerender/local`, but I figured it didn't hurt.

2023-07-06 19:58 UTC, TomWoodward requested changes
can you unprettier it so i can tell what you actually changed please

the project linter will fail according to the project config when necessary

2023-07-07 15:32 UTC, RoyEJohnson commented
Unprettiered.

2023-07-17 17:46 UTC, TomWoodward approved these changes
this is fine, just commented on some extra stuff you're depending on that you don't need

2023-07-17 17:46 UTC, TomWoodward commented on src/app/content/components/Page/contentDOMTransformations.ts
> +  document: Document, rootEl: HTMLElement, intl: IntlShape, services: AppServices & MiddlewareAPI
just services, don't depend on the redux middleware here too

2023-07-17 17:46 UTC, merged