Trap focus in delete-highlight modal
openstax/rex-web pull request #2089
Opened 2023-12-14 19:06 UTC by RoyEJohnson

For: https://github.com/openstax/unified/issues/2698

2023-12-15 21:10 UTC, bethshook approved these changes

2023-12-15 22:47 UTC, jivey requested changes
This is testing well and overall looks good to me, I have a question about skipping disabled elements in the selector.

2023-12-15 22:47 UTC, jivey commented on src/app/reactUtils.ts
> +      'button, [href], input, select, textarea, [tabindex]:not([tabindex="-1"])';
Should we skip `disabled` attributes here? I'm thinking disabled-but-visible inputs could be a concern.

2023-12-15 22:47 UTC, jivey commented on src/app/reactUtils.spec.tsx
> +    // removeEventListener = jest.spyOn(window.document, 'removeEventListener');
Seems like we can remove this

2023-12-20 21:28 UTC, jivey approved these changes

2024-01-11 21:00 UTC, merged