Add aria-label and aria-expanded attributes to DotMenuToggle
openstax/rex-web pull request #2097
Opened 2024-01-02 16:49 UTC by RoyEJohnson

For: https://github.com/openstax/unified/issues/2720

2024-01-05 18:36 UTC, TomWoodward requested changes

2024-01-05 18:36 UTC, TomWoodward commented on src/app/components/DotMenu.tsx
> +        'aria-expanded': isOpen,
you don't have to embed these in the `props` spread, you can define them as normal react props either before or after the `{...props}` depending on which way you want to override

2024-01-08 14:31 UTC, TomWoodward approved these changes

2024-01-08 16:06 UTC, jivey approved these changes

2024-03-22 15:19 UTC, merged