Add default focus style to styled Checkbox
openstax/rex-web pull request #2099
Opened 2024-01-03 20:04 UTC by RoyEJohnson

For: https://github.com/openstax/unified/issues/2713

2024-01-05 18:39 UTC, TomWoodward requested changes

2024-01-05 18:39 UTC, TomWoodward commented on src/app/components/Checkbox.tsx
> +outline: 0.5rem auto -webkit-focus-ring-color;
indent the styles by one please

2024-01-05 18:39 UTC, TomWoodward commented on src/app/components/Checkbox.tsx
> +outline: 0.1rem dotted #212121;
the dotted style is the firefox style, chrome has a blue gradient thing, is it possible to use the default focus styles here implicitly or do we have to use a custom style? or is that what you're doing by defining both the dotted and the webkit at the same time like this?

2024-01-05 23:46 UTC, RoyEJohnson commented on src/app/components/Checkbox.tsx
> +outline: 0.1rem dotted #212121;
I depended on [this StackOverflow post](https://stackoverflow.com/a/38498539), which suggests that you have to spec it. `initial` does not work.

2024-01-08 14:45 UTC, TomWoodward commented on src/app/components/Checkbox.tsx
> +outline: 0.1rem dotted #212121;
ah ok... yea i don't see a simpler solution here since we're doing a hidden-checkbox situation. you may want to just throw that stack overflow link in a comment above the `defaultFocusOutline` style

2024-01-08 14:45 UTC, TomWoodward approved these changes

2024-01-08 16:07 UTC, jivey approved these changes

2024-01-09 22:19 UTC, Malar-Natarajan commented
@RoyEJohnson The CI check `Lint` is failing in this PR. Could you please resolve. Thanks!

2024-01-10 15:24 UTC, merged