Ensure toasts are annnounced by screen readers
openstax/rex-web pull request #2103
Opened 2024-01-08 16:13 UTC by RoyEJohnson

For: https://github.com/openstax/unified/issues/2712
Load ToastContainerWrapper unconditionally, and mark as an alert region.

2024-01-08 17:06 UTC, TomWoodward requested changes
the documentation says:

> Importantly, the element with the ARIA live attributes must be available when the page loads. Otherwise, many screen readers will not detect updates to the element. Additionally, the element must be empty on page load unless an immediate screen reader announcement is desired.

i'm concerned that the alerts won't work unless we add the alert container directly to the index.html template. did you investigate this?

2024-01-09 14:15 UTC, Dantemss reviewed
I'll defer to Tom's review on this one. It may also be helpful to have QA look at this with a screenreader so we know how it behaves.

2024-01-09 14:56 UTC, RoyEJohnson commented
The [documentation](https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Roles/alert_role) only warns that you can't create the alert when you need to use it; that it has to change to be noticed. The screenreader I'm running does encounter the alert and closes it after reading it.
Certainly we'd want QA to confirm that they are getting the desired behavior.

2024-01-09 15:00 UTC, TomWoodward commented
i just want to make sure it works, i'd certainly rather not deal with having only one alert container defined in the index.html that everything has to share access to

2024-01-10 23:22 UTC, RoyEJohnson commented
Is there a process for having QA test it with a screenreader before approving?

2024-01-11 15:08 UTC, TomWoodward commented
@Malar-Natarajan can test it in the heroku env during the normal review phase

2024-01-11 15:12 UTC, TomWoodward requested changes

2024-01-11 15:28 UTC, TomWoodward requested changes

2024-01-11 15:28 UTC, TomWoodward commented on src/app/content/components/Page/PageToasts.tsx
> +  const ref = React.useRef<HTMLElement | null>(null);
this is unused now

2024-01-11 18:07 UTC, TomWoodward approved these changes
as long as the alert works, looks fine to me

2024-01-29 19:53 UTC, merged