Constrain tab navigation in toc
openstax/rex-web pull request #2159
Opened 2024-01-26 21:52 UTC by RoyEJohnson

For: https://github.com/openstax/unified/issues/2753

2024-01-30 14:53 UTC, jivey reviewed
I thought we added `createTrapTab` for stuff like this, maybe it doesn't work for the TOC?

2024-01-30 14:53 UTC, jivey commented on src/app/content/components/TableOfContents/index.tsx
> +    const refIsSensible = mRef && 'current' in mRef && mRef.current;
Suggestion: you could move this directly into the if statement instead of creating an one off variable

2024-01-30 14:53 UTC, jivey commented on src/app/content/components/TableOfContents/index.tsx
> +      {typeof window !== 'undefined' && (
I don't see window accessed, is this here for prerendering?

2024-01-30 14:58 UTC, jivey commented on src/app/content/components/TableOfContents/index.tsx
> +        '[data-testid="navbar"],[data-testid="bookbanner"]'
I'm not sure we want to use testids for functionality, I usually think of these as being free to change for testing purposes.

2024-01-30 15:04 UTC, jivey reviewed
Forget my earlier comment about createTabTrap, I misread the diff and thought we were adding another one. 

Thinking out loud here... in regards to my other comment about the Menu not trapping tab, could we wrap the entire sidebar with a trap? Does this need to target TOC specifically? I wonder if the functionality could be simplified to just check for it being in that entire container or not on mobile/ipad.

2024-01-30 21:54 UTC, RoyEJohnson commented
The overlay that obscures the main content only appears when the TOC is open, so we only trap navigation then.
In addition to the TOC, the sidebar _and_ the title banner _and_ the top nav bar (but _not_ the jump to main content shortcuts) are in the tab cycle.

2024-01-31 14:22 UTC, jivey requested changes
The tablet width + overlay displaying case you mentioned works, I was thinking of the phone width when the main menu / toolbar is open. On a phone, the focus escapes the toolbar (not the TOC.) It feels like we are really close to having this work nicely for both cases. 

Maybe I'm misunderstanding how the trap works or the HTML is structured, but wouldn't targeting `data-testid="toolbar"` and `data-testid="toc"` cycle through the visible elements, making it just work for the mobile case?

2024-02-01 13:57 UTC, jivey approved these changes

2024-02-12 21:34 UTC, merged