Provide accessible label for textarea on EditCard
openstax/rex-web pull request #2175
Opened 2024-02-12 23:44 UTC by RoyEJohnson

For: https://github.com/openstax/unified/issues/2708

2024-02-13 16:32 UTC, jivey requested changes
I was glancing at the associated card and saw a linked figma design, did we decide not to use that?

I saw some likely small bugs, in Firefox the label doesn't look right:
<img width="206" alt="image" src="https://github.com/openstax/rex-web/assets/34174/a9007142-5f53-4cd0-a463-7ddace978075">
and in Chrome, if it's the first time showing the editor and you click the label text directly, it shows the textarea as focused, but it doesn't seem to be (it has no cursor, typing doesn't work)
<img width="214" alt="image" src="https://github.com/openstax/rex-web/assets/34174/7901db46-cec2-44e3-8262-f7f14ec2dee6">

2024-02-13 16:32 UTC, jivey commented on src/app/content/highlights/components/Note.tsx
> +    <WrapperLabel for='note-textarea'>
Do we still need the `for` if the wrapper makes it implicit?

2024-02-14 19:45 UTC, RoyEJohnson commented
The focus issue is addressed in a different PR. The layout should be more like the Figma now (I used blue instead of light blue, because light blue isn't visible enough). Firefox and Safari layout should look right.

2024-02-15 01:41 UTC, jivey approved these changes

2024-03-22 17:07 UTC, merged