Use the new Accounts API to avoid 403 errors
openstax/rex-web pull request #2177
Opened 2024-02-19 17:07 UTC by Dantemss

For: https://github.com/openstax/unified/issues/2476

2024-02-22 20:37 UTC, RoyEJohnson requested changes

2024-02-27 14:51 UTC, RoyEJohnson approved these changes

2024-02-27 14:54 UTC, RoyEJohnson requested changes
I approved too soon.

2024-02-27 15:39 UTC, Dantemss commented
The build test has been broken forever on main... I tried so hard to debug it yesterday but the test browser tab keeps unexpectedly closing and I can't figure out why. Maybe my PR makes it worse though. I'll compare to whatever happens on main.

2024-02-27 18:52 UTC, Dantemss commented
I finally figured it out. I had to update the accounts test fixtures

2024-02-28 17:20 UTC, RoyEJohnson approved these changes

2024-03-12 17:33 UTC, merged