update prerender to include a content manifest csv output
openstax/rex-web pull request #2268
Opened 2024-07-01 21:05 UTC by TomWoodward

adds a csv output of all book toc node info for use by reporting platforms to associate uuids with slugs with titles (for querying and output formatting in reporting dashboards)

also moved sitemap index output to queue generation to avoid loading all the books twice

2024-07-02 23:10 UTC, jivey approved these changes
Looks good just some minor things/questions

2024-07-02 23:10 UTC, jivey commented on script/prerender/sitemap.ts
> +export const contentManifestPath = (pathName: string) => `/rex/manifest/${pathName}.xml`;
I don't think this gets used?

2024-07-02 23:41 UTC, TomWoodward commented on script/prerender/contentManifest.ts
> +    [stripIdVersion(id), title, textTitle, book.language, ...urlParams, tocType, toc_target_type ?? ''],
Yea I doubt that the html will be used by anything but I threw it in there. the text title is intended to be used by reporting I added the context number in there for the eoc pages

2024-07-03 21:37 UTC, jivey requested changes

2024-07-03 21:37 UTC, jivey commented on script/prerender/fleet.ts
> +import { renderAndSaveContentManfiest } from './contentManifest';
Import didn't get renamed

2024-08-09 14:56 UTC, jivey approved these changes

2024-08-09 18:04 UTC, merged