Content warning
openstax/rex-web pull request #2270
Opened 2024-07-03 00:28 UTC by RoyEJohnson

[DISCO-341]

2024-07-03 13:36 UTC, TomWoodward requested changes

2024-07-03 13:36 UTC, TomWoodward commented on src/app/content/components/Page/PageComponent.tsx
> +        <ContentWarning book={this.props.book} />
can you move the usage of this to Content (src/app/content/components
/Content.tsx) and use a redux selector to pull the book in within the component

the PageComponent can be delicate and i don't want to add stuff to it, and moving it to Content will ensure the prompt doesn't show up for assignable users

2024-07-08 17:31 UTC, TomWoodward requested changes
the most recent failure is that the fixture files need to be updated. the fixtures are in `src/test/fixtures/apps/cms/api/v2/pages` and are named by url, so the file name needs to be updated to include the new query parameter, and the body of the file updated to include the expected value for the field

2024-07-09 15:21 UTC, TomWoodward requested changes

2024-07-09 15:21 UTC, TomWoodward commented on src/app/content/components/cookie.ts
> +function tenYearsFromNow() {
there is a cookie npm library that should handle all this stuff in this file

2024-07-09 15:21 UTC, TomWoodward commented on src/app/content/components/ContentWarning.tsx
> +  return new Date(Date.now() + 7 * 24 * 3600 * 1000);
the spec was 28 days

2024-07-12 17:22 UTC, TomWoodward approved these changes

2024-07-12 22:12 UTC, jivey approved these changes

2024-07-16 06:38 UTC, merged