Make highlight Actions menu items (Edit and Delete) buttons
openstax/rex-web pull request #2332
Opened 2024-08-21 17:50 UTC by RoyEJohnson

[DISCO-307]
For clarity, changed `ol` to `menu`
Also simplified return value of DropdownItem.

2024-08-21 22:14 UTC, RoyEJohnson commented
Lint had a problem with the "Stop containers" phase.
<img width="487" alt="image" src="https://github.com/user-attachments/assets/5f6b3db5-1c3d-447a-a302-512c6166e946">

2024-08-23 20:40 UTC, jivey requested changes
The markup changes are great. I need some clarification regarding the card, shouldn't the first menu item get focused? 

There's also a very minor style regression in the MH modal 
![image](https://github.com/user-attachments/assets/c760d3ac-5965-422d-ac55-b00d8d1eb19e)

2024-08-27 13:46 UTC, RoyEJohnson commented
As I read [the comment](https://openstax.atlassian.net/browse/DISCO-307?focusedCommentId=12169), the focus concern is that the "dialog" (the DisplayNote) doesn't get focus when it appears. That is by design; it's what alt-H is for.
In the Disclosure Pattern, the focus does not automatically move from the control button. The user can open and close it repeatedly. They tab to the first revealed item. I'm not finding that to be a hard and fast rule, but it's what I recall LA communicated to us before.
I'll figure out the style regression.

2024-08-27 13:55 UTC, RoyEJohnson commented
1st: using `ol` tag. 2nd: using `menu` tag. 3rd: what's in dev
![image](https://github.com/user-attachments/assets/cc6e2083-506a-4df8-85bd-081fec77d074)
![image](https://github.com/user-attachments/assets/6d1b42bf-247c-4d2f-8889-7b0b4ce4c561)
![image](https://github.com/user-attachments/assets/dc4277ef-25d0-4274-a592-0bd8f745547a)

2024-08-28 15:01 UTC, RoyEJohnson commented
I'm going to have it move focus to the first item.

2024-08-28 16:50 UTC, RoyEJohnson commented
@jivey Focusing on the first item can result in the hover-highlight competing with the focus-highlight, so I had to add code to make focus follow the mouse within the menu.

2024-09-04 14:58 UTC, jivey requested changes
The styles look good, but with the hover change, it can get into a weird state where one item is highlighted by the mouse and the other the keyboard:
<img width="150" alt="image" src="https://github.com/user-attachments/assets/84b623cf-1ce2-4b20-99bd-e70021e6d8dc">

I'm not sure how [react-aria-component's Menu](https://react-spectrum.adobe.com/react-spectrum/Menu.html#menu) handles it  internally, but that seems like a good interaction goal if we can make it work like that.

2024-09-04 20:08 UTC, RoyEJohnson commented
I resolved the focus/hover issue by styling focus and not hover.

2024-09-05 13:56 UTC, jivey approved these changes
Looks good and feels good to use, thanks for going through those review rounds with me.

2025-03-14 22:02 UTC, merged