Add midnight theme
openstax/rex-web pull request #2381
Opened 2024-12-12 16:01 UTC by RoyEJohnson

[CORE-554]

2024-12-12 16:02 UTC, RoyEJohnson commented
I set Nutrition for Nurses to be midnight theme in Dev.
![image](https://github.com/user-attachments/assets/d960b042-cb4a-499b-867a-72e254495382)

2024-12-13 19:53 UTC, jivey approved these changes

2025-02-07 14:20 UTC, TomWoodward requested changes

2025-02-07 14:20 UTC, TomWoodward commented on src/app/content/components/BookBanner.tsx
> +  'midnight': '#003e52',
this looks like the same color as the theme, do we not want this one to have a gradient?

2025-02-10 19:59 UTC, RoyEJohnson commented on src/app/content/components/BookBanner.tsx
> +  'midnight': '#003e52',
I didn't notice those were the light-ends of the gradients. We don't seem to have a midnight gradient set up in osweb (it's using the blue gradient for midnight-theme books), but #005a72 looks nice to me:
![image](https://github.com/user-attachments/assets/9aa36c64-2e40-459d-9e3f-0deff6b8b9b2)

2025-02-12 14:02 UTC, TomWoodward approved these changes

2025-02-12 14:03 UTC, merged