ft. Search sidebar modifications
openstax/rex-web pull request #271
Opened 2019-08-20 20:57 UTC by KarinaMendez2

2019-08-21 14:28 UTC, TomWoodward requested changes

2019-08-21 14:28 UTC, TomWoodward commented on src/app/messages/en/messages.json
> +  "i18n:search-results:bar:query:one-result": "search result for ",
there are formatting options with params you can use for this pluralization, look at the docs for react-intl

2019-08-26 13:00 UTC, kjdav commented
Reviewed for behavior in the a/c; this looks good

2019-08-26 18:47 UTC, TomWoodward approved these changes

2019-08-26 20:05 UTC, TomWoodward approved these changes

2019-08-26 20:59 UTC, merged