track prints to GA
openstax/rex-web pull request #286
Opened 2019-08-29 17:40 UTC by jpslav

Tracks prints to Google Analytics.  The event is registered after the user finishes or cancels the print action.

![image](https://user-images.githubusercontent.com/1001691/63963202-baffd180-ca51-11e9-9007-311418b4b004.png)

2019-09-24 15:17 UTC, TomWoodward requested changes

2019-09-24 16:22 UTC, jpslav commented on src/app/content/print.ts
> -    const slugMatches: string[] | null = pathname.match(/\/books\/(.*)\/pages*/);
goodbye sweet regex designed to annoy tom

2019-09-24 17:37 UTC, TomWoodward requested changes

2019-09-24 17:37 UTC, TomWoodward commented on src/app/content/print.spec.ts
> +    window.location = {...originalLocation, pathname};
this isn't necessary here right?

2019-09-24 17:37 UTC, TomWoodward commented on src/app/content/print.spec.ts
> +    window.location = {...originalLocation, pathname};
or this?

2019-09-24 17:37 UTC, TomWoodward commented on src/app/content/print.spec.ts
> +    window.location = {...originalLocation, pathname: undefined};
or this?

2019-09-24 17:37 UTC, TomWoodward commented on src/app/content/print.spec.ts
> +  });
this tests leaks globals for `window.ga` and `window.print` you should back up the original values and restore them in an `afterEach` like this:

```js
const printBack = window.print;
beforeEach(() => {
  window.print = mockPrint;
});
afterEach(() => {
  window.print = printBack;
})
```

and for the ga too

2019-09-25 16:01 UTC, TomWoodward approved these changes

2019-09-25 18:59 UTC, merged