feat: show and hide solutions
openstax/rex-web pull request #303
Opened 2019-09-09 13:17 UTC by TomWoodward

2019-09-10 22:22 UTC, philschatz requested changes
Ah, here is [an example](https://rex-web-pr-303.herokuapp.com/books/college-physics/pages/2-2-vectors-scalars-and-coordinate-systems#fs-id1788025)

It seems to take a while to hide the element, is that intentional?

![Kapture 2019-09-10 at 17 06 24](https://user-images.githubusercontent.com/253202/64653985-809d1980-d3ed-11e9-9521-8dc4cc4962dc.gif)

It does not seem to expand when search results find text in it. Should it?

![Kapture 2019-09-10 at 17 18 55](https://user-images.githubusercontent.com/253202/64654578-4765a900-d3ef-11e9-8944-7b3e87886d07.gif)


Is @Malar-Natarajan still testing this with a screenreader and with search results?

*Aside:* I was not able to click the search icon when my screen was narrow; is that desired behavior?

*Aside:* It seems _really hard_ to clear the search results. I clicked, entered `speed scalar magnitude`, clicked the `(X)`, reloaded the page, and clicked in the input box and viola! my previous search was back! (see [screencast](https://user-images.githubusercontent.com/253202/64655952-69612a80-d3f3-11e9-9c0c-f0561b7497af.gif))

2019-09-11 13:19 UTC, TomWoodward commented on src/app/content/components/Page.tsx
> +      solution.setAttribute('aria-label', 'show solution');
good call

2019-09-11 13:19 UTC, TomWoodward commented on src/app/content/components/Page.tsx
> +        <div class="ui-toggle-wrapper">
i copied what was already being used on cnx

2019-09-11 13:24 UTC, TomWoodward commented
*It seems to take a while to hide the element, is that intentional?*
its not ideal but we'd need to prerender in the modifications to make this better and this one is complicated enough that i'd want to change the prerendered modifications to run in a dom processor instead of just regex. so i talked with kim about it and we're accepting this behavior for now.

*It does not seem to expand when search results find text in it. Should it?*
malar found this issue, kim decided to make a new card for it.

*Aside: I was not able to click the search icon when my screen was narrow; is that desired behavior?*
i don't recognize this issue, can you give some more details?

*Aside: It seems really hard to clear the search results. I clicked, entered speed scalar magnitude, clicked the (X), reloaded the page, and clicked in the input box and viola! my previous search was back!*
#307  fixes this

2019-09-11 16:37 UTC, philschatz approved these changes
Yay!

2019-09-11 20:54 UTC, merged