Fixed menu offset
openstax/rex-web pull request #412
Opened 2020-01-08 08:59 UTC by janKozie1

2020-01-08 14:50 UTC, TomWoodward requested changes
needs react snaps updated with `yarn test:unit -u`

2020-01-08 21:36 UTC, TomWoodward approved these changes

2020-01-09 01:01 UTC, janKozie1 commented
I'm not sure where do those 5px changes come from. They seem to be quite common? Is there a standard way to fix those? Just update the snapshots?

2020-01-09 14:16 UTC, TomWoodward commented
it happens when the math processing is not totally finished, the snapshots wait for things to be loaded and javascript to finish running but it is very difficult to tell if chrome has actually rendered the stuff yet. if you watch on your screen you can see the math going through several phases of rendering and each one has a different size.

if i get failures in the screenshots like this, or some of the other tests like lighthouse or GA, especially if the two travis tests (branch and PR) don't agree on the results, i just re-run them.

2020-01-16 14:16 UTC, merged