Mh mobile
openstax/rex-web pull request #462
Opened 2020-01-28 15:10 UTC by KarinaMendez2

2020-01-28 15:31 UTC, PiotrKozlowski commented
Filter tags need some padding bottom and button with `data-testid="close-highlights-popup"` could have `line-height: 1` because now `X` icon is aligned to the top of this button.

2020-01-29 15:19 UTC, PiotrKozlowski approved these changes

2020-01-30 16:21 UTC, TomWoodward requested changes

2020-01-31 20:34 UTC, TomWoodward approved these changes

2020-01-31 21:48 UTC, merged