[WIP] useOnEsc hook
openstax/rex-web pull request #473
Opened 2020-01-31 16:20 UTC by PiotrKozlowski

Those tests are tricky and need more work.

2020-02-03 21:05 UTC, TomWoodward requested changes
this approach seems to be working very well. it seems like we have a few places where the focus element is not being managed perfectly though.

2020-02-03 21:05 UTC, TomWoodward commented on src/app/content/highlights/components/Confirmation.tsx
> +    focus={true}
this overlay is not being focused when it is added, i'm not sure this prop does anythign

2020-02-03 21:05 UTC, TomWoodward commented on src/app/content/highlights/components/Card.tsx
> +  useOnEsc(element, props.isFocused, props.blur);
this isn't working when `DisplayNote` is rendered

2020-02-03 21:07 UTC, TomWoodward commented
@PiotrKozlowski i think it would be reasonable to avoid the places which are requiring extra work for now and address those in future pull requests. this is working well in the places where the focus element is set correctly

2020-02-04 13:10 UTC, PiotrKozlowski commented on src/app/content/highlights/components/HighlightsPopUp.tsx
> +      const [addEvListener, removeEvListener] = onEsc(popUp, this.props.closeMyHighlights);
yes

2020-02-04 20:28 UTC, TomWoodward commented
@PiotrKozlowski checks are failing, code looks good thogh

2020-02-06 15:51 UTC, TomWoodward commented
@PiotrKozlowski linter errors
```
src/app/utils.spec.tsx(3,1): error TS6133: 'renderer' is declared but its value is never read.
src/app/utils.spec.tsx(6,1): error TS6133: 'renderToDom' is declared but its value is never read.
```

2020-02-06 17:10 UTC, PiotrKozlowski commented
@TomWoodward Thanks, it looks like `yarn lint:typescript`didn't catch this

2020-02-10 14:48 UTC, TomWoodward approved these changes
the new hook could be moved to the new reactUtils file, but i'm passing to qa now

2020-02-13 15:20 UTC, TomWoodward commented
@PiotrKozlowski i tried this and didn't like the behavior so i did the forwardRef thing you mentioned in https://github.com/openstax/rex-web/pull/496#discussion_r378847619

i think this is good now

2020-02-13 15:38 UTC, PiotrKozlowski commented
@TomWoodward Nice, thanks

2020-02-13 15:56 UTC, merged