Fix highlights by chapter order
openstax/rex-web pull request #477
Opened 2020-02-03 11:30 UTC by janKozie1

Is this approach fine? I will add the tests if it's okay.

2020-02-03 14:01 UTC, PiotrKozlowski requested changes

2020-02-03 14:01 UTC, PiotrKozlowski commented on src/app/content/highlights/components/Highlights.tsx
> +        })
Can you move this sorting logic to `summaryHighlights` selector `src/app/content/highlights/selectors.ts`?
Also: `const orderedPages = findTreePages(location)` should be probably before `sort` so it is not recalculated for every item.

2020-02-03 14:03 UTC, PiotrKozlowski commented on src/app/content/highlights/components/Highlights.tsx
> +        })
or actually create new selector based on `summaryHighlights` so it will be recalculated only if `summaryHighlights` has changed

2020-02-03 14:35 UTC, PiotrKozlowski commented on src/app/content/highlights/components/Highlights.tsx
> +        })
you can also replace `const locationFilters = useSelector(selectors.highlightLocationFilters);` with `const locationFilters = useSelector(selectors.highlightLocationFiltersWithContent);` so we will map only for locations with highlights

2020-02-03 15:23 UTC, TomWoodward commented
@janKozie1 can you explain what the actual error was with safari?

2020-02-03 16:04 UTC, PiotrKozlowski commented
Recording which @annaludwin posted seems not to be related to Safari
I think it might be related to this code: from `updateSummaryHighlightsDependOnFilters`
```
let newHighlights: SummaryHighlights = {
    ...summaryHighlights,
    [locationFilterId]: {
      ...summaryHighlights[locationFilterId],
      [pageId]: [...(summaryHighlights[locationFilterId] || {})[pageId] || []],
    },
  };
```
we are adding `[pageId]` at the and of object which then is rendered also at the end?

This code will be removed with https://github.com/openstax/rex-web/pull/478 so this actually will not need any more work?

2020-02-04 17:25 UTC, janKozie1 commented
I was able to replicate  in Calculus Volume 1 - functions and graphs by:
- adding a highlight in 1.3
- adding a highlight in 1.5
- adding a highlight in 1.1

2020-02-04 20:50 UTC, TomWoodward requested changes

2020-02-04 20:50 UTC, TomWoodward commented on src/app/content/highlights/selectors.ts
> +    return getSortedSummeryHighlights(state.summary.highlights, locationFilters);
if what you want is `highlights` you should depend on `summaryHighlights` not `localState` so the memoization works better

2020-02-04 20:50 UTC, TomWoodward commented on src/app/content/highlights/utils/summaryHighlightsUtils.ts
> +export const getSortedSummeryHighlights =
```suggestion
export const getSortedSummaryHighlights =
```

2020-02-04 20:50 UTC, TomWoodward commented on src/app/content/highlights/utils/summaryHighlightsUtils.ts
> +  (summaryHighlights: SummaryHighlights | null, locationFilters: HighlightLocationFilters ) => {
does this function return `SummaryHighlights`? objects have no implicit order in javascript, so if this is supposed to sort things we should really be returning an array

2020-02-05 12:53 UTC, PiotrKozlowski requested changes
It looks good, I've left two comments, but I think you can start adding tests

2020-02-05 12:53 UTC, PiotrKozlowski commented on src/app/content/highlights/selectors.ts
> +  (state) => state.summary.highlights
It seems like this change is unnecessary

2020-02-05 12:53 UTC, PiotrKozlowski commented on src/app/content/highlights/utils/summaryHighlightsUtils.ts
> +      ];
Can we simplify this to something like: ?
```
const pages: OrderedSummaryHighlights[0]['pages'] = [];

      for (const page of orderedPages) {
        if (!summaryHighlights[locationID][page.id]) { continue; }
        pages.push({
          highlights: summaryHighlights[locationID][page.id],
          pageId: page.id,
        });
      }

      return [
        ...previousLocations,
        {
          location,
          pages,
        },
      ];
```

2020-02-05 14:37 UTC, janKozie1 commented
I don't think the test for `SectionHighlights` to throw is necessary anymore since the pages are based on `findTreePages(location)`

2020-02-05 15:16 UTC, PiotrKozlowski approved these changes

2020-02-05 20:41 UTC, TomWoodward requested changes

2020-02-05 20:41 UTC, TomWoodward commented on src/app/content/highlights/components/Highlights.tsx
> +        .map(({pageId, highlights}) => {
this line break doesn't really have to be here

2020-02-05 20:56 UTC, janKozie1 commented
@TomWoodward updated

2020-02-05 21:14 UTC, TomWoodward approved these changes
wait for qa review before merging

2020-02-11 22:06 UTC, merged