[WIP] Add makeApiCallOrThrow util function
openstax/rex-web pull request #509
Opened 2020-02-17 16:21 UTC by PiotrKozlowski

@TomWoodward I have a problem with tests for `create/remove/updateHighlight.ts`
For some reason, `makeApiCallOrThrow` is getting `undefined` instead of a promise.

2020-02-17 18:54 UTC, TomWoodward requested changes

2020-02-17 18:54 UTC, TomWoodward commented on src/app/content/highlights/hooks/createHighlight.ts
> +  await makeApiCallOrThrow(highlightClient.addHighlight({highlight: payload}));
is it possible to add this to the fetch call in `src/gateways/createHighlightClient.ts` instead of in every place the api is called from?

2020-02-17 18:54 UTC, TomWoodward commented on src/app/utils.ts
> +      throw new Error(error);
i feel like you're this is going to potentially nest things that shouldn't be nested. maybe doing 
```
return Promise.reject(error);
```

would be better? i'm assuming what you're being passed in this handler is already an error, so nesting it in another error object might not be ideal

2020-02-18 14:40 UTC, TomWoodward requested changes
this isn't working. after a fetch the promise won't be rejected unless it literally failed to connect to the server. its only in subsequent sdk code that it inspects the response and rejects the promise. 

i think we have to expand the `src/gateways/createHighlightClient.ts` file to proxy all the calls to the client so that we can append the error handler to the returned promises after the sdk error handling

2020-02-18 14:49 UTC, TomWoodward commented
looking at the sdk code, there is not significant logic in there. so maybe we don't have to worry too much about doing our own thing with the fetch response.

if you want, you can continue doing as you are with the fetchApi handler, and just add some response inspection stuff. i have utilities i've used for this before in `src/helpers/fetch.ts`, but the `acceptStatus` function only takes one argument so you'd have to change it to take a list of acceptable statuses

2020-02-19 13:56 UTC, PiotrKozlowski commented
`acceptStatus` was hard to reuse because of `rejectResponse` process response as `text` and `formatError` type is expecting different arguments in this case so I've decided it will be simpler to just write this on it's own

2020-02-19 14:51 UTC, TomWoodward approved these changes
thats fine, what you have looks good now

2020-02-19 14:55 UTC, merged