Add styling for highlight indicator
openstax/rex-web pull request #532
Opened 2020-03-02 14:03 UTC by PiotrKozlowski

for: https://app.zenhub.com/workspaces/openstax-unified-5b71aabe3815ff014b102258/issues/openstax/unified/864

connected with: https://github.com/openstax/highlighter/pull/34

Add an indicator for the text highlights.

2020-03-04 16:11 UTC, KarinaMendez2 requested changes

2020-03-04 16:11 UTC, KarinaMendez2 commented on src/app/content/components/Page/PageContent.tsx
> +          border-left: 0.8rem solid transparent;
this could use a variable for 0.8rem if there isn't one already

2020-03-04 16:21 UTC, KarinaMendez2 approved these changes
I don't have access to the designs for this card and issue to check that part but code looks good.

2020-03-04 18:48 UTC, janKozie1 requested changes

2020-03-04 18:48 UTC, janKozie1 commented on src/app/content/components/Page/PageContent.tsx
> +          transform: rotate(-45deg);
I played around with this and was able to recreate it with 
```
position: absolute;
top: 0rem;
left: 0rem;
content: "";
width: 0;
height: 0;
border-left: 1.1rem solid #fed200;
border-top: 1.1rem solid transparent;
transform: rotate(90deg);
``` 
I think `0` for `top` and `left` will be a bit more reliable

2020-03-05 17:20 UTC, janKozie1 approved these changes

2020-03-10 14:42 UTC, TomWoodward commented
@PiotrKozlowski i published version `1.5.1` of the highlighter with your changes

2020-03-10 14:55 UTC, TomWoodward requested changes

2020-03-10 14:55 UTC, TomWoodward commented on src/app/content/components/Page/PageContent.tsx
> +      &.first.text {
can't this be 
```suggestion
      &.first.text:before {
```

2020-03-10 14:55 UTC, TomWoodward commented on src/app/content/components/Page/PageContent.tsx
> +  }
these styles make me nervous, i'll need to do some testing once you update the highlighter library to make sure that:

- the padding doesn't move anything on the page
- the position doesn't break math or other elements inside the highlight spans, and doesn't break text wrapping or anything like that

2020-03-10 14:55 UTC, TomWoodward commented on src/app/content/components/Page/PageContent.tsx
> +          border-left: ${highlightIndicatorSize}rem solid ${style.focused};
the size of the highlight indicator might be a good time to use `em`s since for instance figure caption text is smaller than regular text

2020-03-10 15:01 UTC, PiotrKozlowski commented
@TomWoodward I've pushed changes

2020-03-10 18:30 UTC, TomWoodward requested changes
some issues:
- the indicator should only be present if there is a note
- the old note indicator (the border-bottom) is still there, we need to remove that

i think you added the padding to make it look more like the design, but i worry about overflowing the line like that, it makes it look weird when you have nearby highlights, like this:

![image](https://user-images.githubusercontent.com/636227/76346553-99728300-62db-11ea-965d-b1f57b6f43b6.png)

please consult devika on this issue

2020-03-11 13:04 UTC, PiotrKozlowski commented
I've pushed requested changes and started a thread about highlight overlapping: https://openstax.slack.com/archives/C8V1XET1R/p1583931744255000

2020-03-12 12:57 UTC, PiotrKozlowski commented
@TomWoodward After a conversation with Devika I've removed padding-top and moved indicator behind the text.

2020-03-18 14:50 UTC, PiotrKozlowski commented
The positioning indicator between the text and the background-color works only in Firefox.
We are discussing new design for this: https://openstax.slack.com/archives/C8V1XET1R/p1584542254410000

2020-03-19 21:13 UTC, TomWoodward approved these changes

2020-03-23 17:21 UTC, merged