Add aria labels to MH - chapter and section titles
openstax/rex-web pull request #537
Opened 2020-03-05 14:39 UTC by KarinaMendez2

and section title in mh popup

2020-03-06 12:48 UTC, PiotrKozlowski approved these changes

2020-03-11 14:25 UTC, TomWoodward approved these changes
aria labels are supposed to be human readable labels for screen readers to generate text for things that would otherwise be impossible for it to derive meaning from, for instance buttons with only icons inside.

if you can't come up with something useful to put in an `aria-label` and you just need some kind of something on it to help the automated tests, use a `data-testid` instead

2020-03-11 14:25 UTC, TomWoodward requested changes
previous comment

2020-03-13 17:22 UTC, TomWoodward approved these changes

2020-03-23 13:35 UTC, merged