Add config for content links
openstax/rex-web pull request #548
Opened 2020-03-13 19:40 UTC by KarinaMendez2

2020-03-17 15:55 UTC, PiotrKozlowski commented
The code looks okay.

2020-03-18 16:06 UTC, PiotrKozlowski approved these changes
Tested for link: https://localhost:3000/books/f0fa90be-fca8-43c9-9aad-715c0a2cee2b@1.3/pages/6-3-solve-sales-tax-commission-and-discount-applications

2020-03-20 17:38 UTC, TomWoodward requested changes

2020-03-20 17:38 UTC, TomWoodward commented on src/app/content/hooks/locationChange/resolveContent.ts
> +  const devEnvironment = UNLIMITED_CONTENT;
please just replace your usage on line 170 rather than aliasing this variable like this

2020-03-23 17:53 UTC, TomWoodward approved these changes

2020-03-23 17:53 UTC, merged