FE Selenium test: validate cookie notice
openstax/rex-web pull request #636
Opened 2020-05-18 22:15 UTC by Malar-Natarajan

C546505: users who 'got it' in osweb should not get cookie notice in rex 
C546506: users who did not 'got it' in osweb should get cookie notice in rex
C546507: users who 'got it' in a previous session in a browser should not get the notice again
C5465078: users who 'got it' in Rex should not get cookie notice in osweb 
C5465079: users who did not 'got it' in Rex should get cookie notice in osweb

2020-05-18 22:26 UTC, Malar-Natarajan commented
@gregfitch  when you have a chance please review this PR

2020-05-22 14:29 UTC, TomWoodward approved these changes
preemptively approving this because the codeowner is set wrong, greg should still review

2020-05-26 14:15 UTC, gregfitch requested changes

2020-05-26 14:15 UTC, gregfitch commented on pytest-selenium/pages/osweb.py
> +    def notification_dialog_displayed(self) -> bool:
Because this is a simple state on the page (bool) and not an action, this should be a `@property`.

2020-05-26 14:15 UTC, gregfitch commented on pytest-selenium/pages/osweb.py
> +        self.wait.until(lambda _: not self.notification_dialog_displayed())
With the previous comment, this becomes:
`lambda _: not self.notification_dialog_displayed`

2020-05-27 14:02 UTC, Malar-Natarajan commented
@gregfitch I have updated tests based on your comments. Please re-review

2020-05-27 14:37 UTC, gregfitch approved these changes

2020-05-27 21:21 UTC, Malar-Natarajan commented
@TomWoodward all checks pass. please merge this pr

2020-06-01 15:54 UTC, merged