Issue 1213
openstax/rex-web pull request #738
Opened 2020-07-28 16:07 UTC by PiotrKozlowski

for: https://github.com/openstax/unified/issues/1213

2020-07-28 17:19 UTC, janKozie1 reviewed
You could write a test with timeouts if you wanted to replicate the problem. 
Left some minor comments too.

2020-07-28 17:19 UTC, janKozie1 commented on src/app/content/highlights/hooks/loadMore.spec.ts
> +    filters = store.getState().content.highlights.summary.filters;
Do the filters get changed somewhere?

2020-07-28 17:19 UTC, janKozie1 commented on src/app/content/highlights/reducer.spec.ts
> +      const staleFilters = {} as any as SummaryFilters;
You could add `locationIds: [], colors: []` into the object and it wouldn't need to be casted.

2020-07-29 15:54 UTC, janKozie1 approved these changes

2020-07-30 16:55 UTC, TomWoodward requested changes

2020-07-30 16:55 UTC, TomWoodward commented on src/app/content/highlights/reducer.ts
> +      if (action.meta.filters && !equals(state.summary.filters, action.meta.filters)) { return state; }
you can use strict equality here, i don't think lodash equals is necessary

2020-08-06 14:05 UTC, TomWoodward approved these changes

2020-08-10 14:35 UTC, merged