Prealgebra updates
openstax/rex-web pull request #856
Opened 2020-09-18 05:04 UTC by staxbot

2020-09-24 13:16 UTC, janKozie1 requested changes

2020-09-24 13:16 UTC, janKozie1 commented on src/canonicalBookMap/preAlgebra.ts
> +    /* Pre Algebra 2e */ ['caa57dab-41c7-455e-bd6f-f443cda5519c', {
Those ids should be other way around.

2020-09-24 14:24 UTC, janKozie1 approved these changes

2020-10-13 14:10 UTC, Malar-Natarajan approved these changes

2020-10-13 14:17 UTC, merged