Elementary Algebra updates
openstax/rex-web pull request #857
Opened 2020-09-18 05:05 UTC by staxbot

2020-09-25 13:13 UTC, janKozie1 requested changes

2020-09-25 13:13 UTC, janKozie1 commented on src/canonicalBookMap/elementaryAlgebra.ts
> +      '4b5aaf32-1de1-419b-bdc0-4e0a7f6daf0f' :	'4b5aaf32-1de1-419b-bdc0-4e0a7f6daf0f',
These ids are the same. You should probably report it

2020-09-25 14:50 UTC, janKozie1 approved these changes

2020-10-13 14:12 UTC, Malar-Natarajan approved these changes

2020-10-13 19:25 UTC, merged